package com.sample
  
import com.sample.Window;

global Window okno;

declare Pytanie
	tresc : String
	odpowiedz1 : String
	odpowiedz2 : String
end

declare Odpowiedz
	pytanie : Pytanie
	odpowiedz : String
	
end

rule "Init"
	when
	then
		insert(new Pytanie("Do you want to avoid using much of your brain?", "Yes","No"));
		okno = new Window();
		insert(okno);
end
 
rule "Pytanie 1"
    when p : Pytanie()
    then
    	String odp = okno.zadajPytanie(p.getTresc(),p.getOdpowiedz1(),p.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(p, odp);
    	insert(o);
end

rule "Pytanie 2"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to avoid using much of your brain?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("How are your reflexes?","Unreal","Average");
    	String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Pytanie 3"
	when Odpowiedz(p : pytanie, p.getTresc() == "How are your reflexes?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Are you on drugs?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt, odp);
    	insert(o);
end

rule "Rez"
	when Odpowiedz(p : pytanie, p.getTresc() == "Are you on drugs?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Rez");
end

rule "Pytanie 4"
	when Odpowiedz(p : pytanie, p.getTresc() == "Are you on drugs?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Do you want to feel like you are?", "Yes", "No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Geometry Wars 2"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to feel like you are?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Geometry Wars 2");
end

rule "Pytanie 5"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to feel like you are?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("How's your timing?","Superb","Average");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Pytanie 6"
	when Odpowiedz(p : pytanie, p.getTresc() == "How's your timing?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("You want to rock out?", "Yes", "No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Rockband 3"
	when Odpowiedz(p : pytanie, p.getTresc() == "You want to rock out?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Rockband 3");		
end

rule "Ikaruga"
	when Odpowiedz(p : pytanie, p.getTresc() == "You want to rock out?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Ikaruga");
end

rule "Pytanie 7"
	when Odpowiedz(p : pytanie, p.getTresc() == "How's your timing?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Are 2 buttons too many for you?", "Yes", "No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Ms. Pac-Man"
	when Odpowiedz(p : pytanie, p.getTresc() == "Are 2 buttons too many for you?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Ms. Pac-Man");
end

rule "Super Punch-Out!"
	when Odpowiedz(p : pytanie, p.getTresc() == "Are 2 buttons too many for you?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Super Punch-Out!");
end

rule "Pytanie 8"
	when Odpowiedz(p : pytanie, p.getTresc() == "How are your reflexes?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Do you want to point and click click click click click click... ?","No","Yes");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz2(),pyt.getOdpowiedz1());
    	Odpowiedz o = new Odpowiedz(pyt, odp);
    	insert(o);
end

rule "Pytanie 9"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to point and click click click click click click... ?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Do you want the hardest game ever?", "No", "Yes");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz2(),pyt.getOdpowiedz1());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Super Monkey Ball"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want the hardest game ever?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Super Monkey Ball");
end


rule "Devil May Cry 3"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want the hardest game ever?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Devil May Cry 3");
end

rule "Pytanie 10"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to point and click click click click click click... ?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Do you plan on playing for the next week straight?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "World Of Warcraft"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you plan on playing for the next week straight?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("World Of Warcraft");
end


rule "Diablo II"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you plan on playing for the next week straight?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Diablo II");
end

rule "Pytanie 11"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to avoid using much of your brain?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Maximum Creativity?","No","Yes");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz2(),pyt.getOdpowiedz1());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Minecraft"
	when Odpowiedz(p : pytanie, p.getTresc() == "Maximum Creativity?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Minecraft");
end

rule "Pytanie 12"
	when Odpowiedz(p : pytanie, p.getTresc() == "Maximum Creativity?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Do you want to solve some puzzle?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Pytanie 13"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to solve some puzzle?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Do you feel the need for a storyline as well?","No","Yes");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz2(),pyt.getOdpowiedz1());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Pytanie 14"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you feel the need for a storyline as well?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Kick it oldschool?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Tetris"
	when Odpowiedz(p : pytanie, p.getTresc() == "Kick it oldschool?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Tetris");
end

rule "Lumines Electronic Symphony"
	when Odpowiedz(p : pytanie, p.getTresc() == "Kick it oldschool?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Lumines Electronic Symphony");
end	
	
rule "Pytanie 15"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you feel the need for a storyline as well?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Are you an Edward Gorey fan?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end	

rule "Limbo"
	when Odpowiedz(p : pytanie, p.getTresc() == "Are you an Edward Gorey fan?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Limbo");
end

rule "Pytanie 16"
	when Odpowiedz(p : pytanie, p.getTresc() == "Are you an Edward Gorey fan?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Looking for crazy Japanese awesomeness?","No","Yes");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz2(),pyt.getOdpowiedz1());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end	
	
rule "Katamari Damacy"
	when Odpowiedz(p : pytanie, p.getTresc() == "Looking for crazy Japanese awesomeness?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Katamari Damacy");
end

rule "Pytanie 17"
	when Odpowiedz(p : pytanie, p.getTresc() == "Looking for crazy Japanese awesomeness?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Do you want shiny textures or indi magic?","Indi","Shiny");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end
		
rule "Braid"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want shiny textures or indi magic?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Braid");
end

rule "Portal 2"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want shiny textures or indi magic?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Portal 2");
end

rule "Pytanie 18"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to solve some puzzle?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Do you enjoy simulations?","No","Yes");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz2(),pyt.getOdpowiedz1());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Pytanie 19"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you enjoy simulations?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Button mashable?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end
		
rule "Pytanie 20"
	when Odpowiedz(p : pytanie, p.getTresc() == "Button mashable?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Does realistic violence upset you?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Super Smash Bros"
	when Odpowiedz(p : pytanie, p.getTresc() == "Does realistic violence upset you?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Super Smash Bros");
end

rule "Pytanie 21"
	when Odpowiedz(p : pytanie, p.getTresc() == "Does realistic violence upset you?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Do you like big-ass weapons?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Soulcalibur II"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you like big-ass weapons?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Soulcalibur II");
end

rule "Pytanie 22"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you like big-ass weapons?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Do you want to tear out your opponent's spine?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Mortal Kombat Deception"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to tear out your opponent's spine?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Mortal Kombat Deception");
end

rule "Super Street Fighter IV"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to tear out your opponent's spine?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Super Street Fighter IV");
end

rule "Pytanie 23"
	when Odpowiedz(p : pytanie, p.getTresc() == "Button mashable?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Does you own any official team jerseys?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "EA Sports"
	when Odpowiedz(p : pytanie, p.getTresc() == "Does you own any official team jerseys?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("EA Sports");
end

rule "Pytanie 24"
	when Odpowiedz(p : pytanie, p.getTresc() == "Does you own any official team jerseys?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Does the sound of squealing tires excite you?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Pytanie 25"
	when Odpowiedz(p : pytanie, p.getTresc() == "Does the sound of squealing tires excite you?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Should racing games be based in reality?","No","Yes");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz2(),pyt.getOdpowiedz1());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Pytanie 26"
	when Odpowiedz(p : pytanie, p.getTresc() == "Should racing games be based in reality?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		Pytanie pyt = new Pytanie("Super speed or turtle shells?","Shells","Speed");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Mario Kart 64"
	when Odpowiedz(p : pytanie, p.getTresc() == "Super speed or turtle shells?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Mario Kart 64");
end

rule "F-ZERO GX"
	when Odpowiedz(p : pytanie, p.getTresc() == "Super speed or turtle shells?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("F-ZERO GX");
end

rule "Pytanie 27"
	when Odpowiedz(p : pytanie, p.getTresc() == "Should racing games be based in reality?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("You want to be a badass?","Yes","No");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Burnout Paradise"
	when Odpowiedz(p : pytanie, p.getTresc() == "You want to be a badass?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Burnout Paradise");
end

rule "Pytanie 28"
	when Odpowiedz(p : pytanie, p.getTresc() == "You want to be a badass?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Rally or Track?","Rally","Track");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Sega Rally"
	when Odpowiedz(p : pytanie, p.getTresc() == "Rally or Track?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Sega Rally");
end

rule "Gran Turismo 3 A-spec"
	when Odpowiedz(p : pytanie, p.getTresc() == "Rally or Track?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Gran Turismo 3 A-spec");
end

rule "Pytanie 29"
	when Odpowiedz(p : pytanie, p.getTresc() == "Does the sound of squealing tires excite you?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Do you think professional wrestling is stupid?","No","Yes");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz2(),pyt.getOdpowiedz1());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "WWF No Mercy"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you think professional wrestling is stupid?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("WWF No Mercy");
end

rule "Pytanie 30"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you think professional wrestling is stupid?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Skate or die putt?","Skate","Putt");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "Tony Hawk's Pro Skater 3"
	when Odpowiedz(p : pytanie, p.getTresc() == "Skate or die putt?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("Tony Hawk's Pro Skater 3");
end

rule "Hot Shots Golf Open tee 2"
	when Odpowiedz(p : pytanie, p.getTresc() == "Skate or die putt?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Hot Shots Golf Open tee 2");
end

rule "Pytanie 31"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you enjoy simulations?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		Pytanie pyt = new Pytanie("Do you want to be in charge of a life or an entire city?","Life","City");
		String odp = okno.zadajPytanie(pyt.getTresc(),pyt.getOdpowiedz1(),pyt.getOdpowiedz2());
    	Odpowiedz o = new Odpowiedz(pyt,odp);
    	insert(o);
end

rule "The Sims 3"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to be in charge of a life or an entire city?" && getOdpowiedz() == p.getOdpowiedz1())
	then
		okno.koniec("The Sims 3");
end

rule "Sim City 2000"
	when Odpowiedz(p : pytanie, p.getTresc() == "Do you want to be in charge of a life or an entire city?" && getOdpowiedz() == p.getOdpowiedz2())
	then
		okno.koniec("Sim City 2000");
end
